export const INTEGER_VAR_VALUES: { value: string; label: string }[] = [
	{ value: '自定义值', label: '自定义值' },
	{ value: '道具数量返回', label: '道具数量返回' },
	{ value: '精灵数量返回1', label: '精灵数量返回1' },
	{ value: '精灵数量返回2', label: '精灵数量返回2' },
	{ value: '背包精灵catchtime返回', label: '背包精灵catchtime返回' },
	{ value: '背包精灵catchtime返回2', label: '背包精灵catchtime返回2' },
	{ value: '用户当前超NO状态返回', label: '用户当前超NO状态返回' },
	{ value: '用户当前年费状态返回', label: '用户当前年费状态返回' },
	{ value: '用户当前火焰状态返回', label: '用户当前火焰状态返回' },
	{ value: '现行10位时间戳', label: '现行10位时间戳' },
	{ value: '当前星期几', label: '当前星期几' },
	{ value: '当前年份', label: '当前年份' },
	{ value: '当前月份', label: '当前月份' },
	{ value: '当前日', label: '当前日' },
	{ value: '当前小时', label: '当前小时' },
	{ value: '当前分钟', label: '当前分钟' },
	{ value: '当前秒数', label: '当前秒数' },
	{ value: '时间戳取年份', label: '时间戳取年份' },
	{ value: '时间戳取月份', label: '时间戳取月份' },
	{ value: '时间戳取日', label: '时间戳取日' },
	{ value: '时间戳取小时', label: '时间戳取小时' },
	{ value: '时间戳取分钟', label: '时间戳取分钟' },
	{ value: '时间戳取秒数', label: '时间戳取秒数' },
];

export const STRING_VAR_VALUES: { value: string; label: string }[] = [
	{ value: '自定义文本', label: '自定义文本' },
	{ value: '游戏收包主体文本返回', label: '游戏收包主体文本返回' },
	{ value: '现行时间', label: '现行时间' },
	{ value: '时间戳转文本', label: '时间戳转文本' },
];

export const NO_CUSTOM_VAR_TYPES: string[] = [
	'用户当前超NO状态返回',
	'用户当前年费状态返回',
	'用户当前火焰状态返回',
	'现行10位时间戳',
	'当前星期几',
	'当前年份',
	'当前月份',
	'当前日',
	'当前小时',
	'当前分钟',
	'当前秒数',
	'现行时间',
];